import countries

croatia = countries.croatia()
norway = countries.norway()
greece = countries.greece()
albania = countries.albania()
germany = countries.germany()
denmark = countries.denmark()
hungary = countries.hungary()
poland = countries.poland()
italy = countries.italy()
slovakia = countries.slovakia()
france = countries.france()
macedonia = countries.macedonia()
austria = countries.austria()
spain = countries.spain()
united_kingdom = countries.united_kingdom()
portugal = countries.portugal()
sweden = countries.sweden()
netherlands = countries.netherlands()
serbia = countries.serbia()
switzerland = countries.switzerland()
belgium = countries.belgium()
slovenia = countries.slovenia()
czechia = countries.czechia()